apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valuesFiles:
        - values-staging.yaml
    path: helm
    repoURL: https://github.com/EmekaMomodu/TechTrends
    targetRevision: HEAD
  syncPolicy: {}
